name: Go
on:
  push:
    branches:
      - main

env:
  REGISTRY: quay.io
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:

  release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build chart
        run: |
          helm package helm-chart

      - name: Add chart
        run: |
          shopt -s nullglob
          filename=(bchr-test-*.tgz)
          if [ -z "$filename" ]; then
            echo "No chart found"
            exit 1
          fi
          if [ -f "gh-pages/$filename" ]; then
            echo "Chart $filename already exists"
            exit 1
          fi
          mv "$filename" gh-pages/
          helm repo index gh-pages/

      - name: Index chart Git
        run: |
          git config user.name github-chart-bot
          git config user.email "github-chart-bot@users.noreply.github.com"
          git add --all
          git commit -m "Update chart"
        working-directory: gh-pages

      - name: Push chart
        run: |
          git push origin gh-pages
        working-directory: gh-pages
